version: '3.8'

services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
