spring:
  application:
    name: codi-api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
  datasource:
    url: jdbc:h2:mem:localtest
    driverClassName: org.h2.Driver
    username: sa
    generate-unique-name: false
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 30
      max-lifetime: 30000
  elasticsearch:
    uris: http://elasticsearch:9200
